In [1]:
import pandas as pd
import numpy as np
import gc
from IPython.display import display
from mnp.ingestion.loader import load_endes
from mnp.utils.profiler import centrar_notebook
from mnp.utils.cleaning import run_phase1_engine, apply_standard_labels

# Configuración visual
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
centrar_notebook()

print("[OK]")

2026-06-16 16:42:45.178 | INFO     | mnp.config:<module>:11 - PROJ_ROOT path is: /Users/abelguevarah/Desktop/invs/malnutrition-research

[OK]

In [2]:
# Carga de datos
history = load_endes(
        year=range(2007, 2025),
        module="maternal_health",
        record="rec41",
        meta=True
    )

dfs = []
col_labels_hist = {}
val_labels_hist = {}

for year in sorted(list(history.keys())):
    year_df, year_meta = history.pop(year)
    col_labels_hist[year] = year_meta.column_names_to_labels
    val_labels_hist[year] = year_meta.variable_value_labels
    
    dfs.append(year_df.assign(year=year))

df_raw = pd.concat(dfs, ignore_index=True)
del dfs
gc.collect()

print(f"[OK] Data REC41 cargada: {len(df_raw)} filas y {df_raw.shape[1]} columnas.")
print(f"[OK] Diccionario cargado: {len(col_labels_hist)} Column Labels, {len(val_labels_hist)} Value Labels")

2026-06-16 16:42:45.339 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:45.662 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:45.984 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:46.242 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:46.486 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.sav desde Modulo69 [Alias: rec41]
2026-06-16 16:42:46.727 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.sav desde Modulo69 [Alias: rec41]
2026-06-16 16:42:47.022 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:47.290 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:47.549 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:48.249 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:48.880 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:49.424 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo69 [Alias: rec41]
2026-06-16 16:42:50.015 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.sav desde Modulo69 [Alias: rec41]
2026-06-16 16:42:50.620 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.sav desde Modulo1633 [Alias: rec41]
2026-06-16 16:42:51.066 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.SAV desde Modulo1633 [Alias: rec41]
2026-06-16 16:42:51.694 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41.sav desde Modulo1633 [Alias: rec41]
2026-06-16 16:42:52.277 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41_2023.sav desde Modulo1633 [Alias: rec41]
2026-06-16 16:42:52.823 | INFO     | mnp.ingestion.loader:load_endes:378 - ✓ Cargando registro: REC41_2024.sav desde Modulo1633 [Alias: rec41]
2026-06-16 16:42:53.345 | SUCCESS  | mnp.ingestion.loader:_load_multiple_years:293 - ✅ ¡Historia cargada y organizada por años!
[OK] Data REC41 cargada: 292824 filas y 148 columnas.
[OK] Diccionario cargado: 18 Column Labels, 18 Value Labels

In [3]:
from mnp.configs.rec41 import config_f1

# 3. Limpiar Fase 1 (Numéricos / Falsos Numéricos / Casteos)
df_clean = run_phase1_engine(df_raw, config_f1)

print(f'[OK] Limpieza biológica Fase 1 completa. Shape: {df_clean.shape}')
df_clean.head(10)

[Limpieza] Iniciando Motor Fase 1...
[Limpieza] Eliminando 1 columnas (Optimización RAM)...
[Limpieza] Drops iniciales completados en 0.00s
[Limpieza] Casteando 2 columnas clave...
[Limpieza] Casteo completado en 0.43s
[Limpieza] Limpiando falsos numéricos...
[Limpieza] Falsos numéricos limpiados en 0.11s
[Limpieza] Aplicando reemplazos custom...
[Limpieza] Reemplazos custom completados en 0.00s
[Limpieza] Motor Fase 1 finalizado. Tiempo total: 0.55s
[OK] Limpieza biológica Fase 1 completa. Shape: (292824, 147)

,CASEID,MIDX,M1,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E,M2F,M2G,M2H,M2I,M2J,M2K,M2L,M2M,M2N,M3A,M3B,M3C,M3D,M3E,M3F,M3G,M3H,M3I,M3J,M3K,M3L,M3M,M3N,M4,M5,M6,M7,M8,M9,M10,M11,M13,M14,M15,M17,M18,M19,M19A,M27,M28,M29,M34,M35,M36,M38,M39,M42A,M42B,M42C,M42D,M42E,M43,M44,M45,M46,M47,M48,M49A,M49B,M49C,M49D,M49E,M49F,M49G,M49X,M49Z,M51A,M54,M55A,M55B,M55C,M55D,M55E,M55F,M55G,M55H,M55I,M55J,M55K,M55L,M55M,M55N,M55X,M55Z,M57A,M57B,M57C,M57D,M57E,M57F,M57G,M57H,M57I,M57J,M57K,M57L,M57M,M57N,M57O,M57P,M57Q,M57R,M57S,M57T,M57U,M57V,M57X,M60,M61,M62,M63,M64,M65A,M65B,M65C,M65D,M65E,M65F,M65G,M65H,M65I,M65J,M65K,M65L,M65X,M66,M67,M68,M69,M70,M71,M72,M73,year
0,1 10 2,1,0.0,5.0,NaN,NaN,4.0,1210.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,9.0,9.0,12.0,12.0,3.0,3.0,1.0,NaN,3.0,9.0,21.0,1.0,3.0,2950.0,1.0,0.0,0.0,0.0,101.0,NaN,NaN,1.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,103.0,11.0,21.0,1.0,NaN,NaN,NaN,2007
1,1 22 2,1,2.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,17.0,17.0,1.0,1.0,3.0,3.0,3.0,NaN,3.0,9.0,21.0,0.0,3.0,3100.0,1.0,0.0,0.0,0.0,112.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,0.0,NaN,1.0,18.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,118.0,11.0,21.0,1.0,NaN,NaN,NaN,2007
2,1 34 2,1,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,18.0,18.0,9.0,9.0,1.0,1.0,1.0,NaN,3.0,6.0,22.0,0.0,3.0,3600.0,2.0,0.0,0.0,0.0,102.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,30.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,1.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,110.0,12.0,22.0,1.0,NaN,NaN,NaN,2007
3,2 9 2,1,3.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,20.0,20.0,1.0,1.0,1.0,1.0,2.0,209.0,1.0,8.0,11.0,0.0,3.0,3300.0,2.0,0.0,0.0,0.0,101.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,0.0,1.0,1.0,1.0,1.0,30.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,100.0,11.0,11.0,1.0,100.0,11.0,11.0,2007
4,2 9 2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,19.0,19.0,96.0,10.0,10.0,10.0,2.0,202.0,NaN,NaN,NaN,0.0,3.0,3300.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007
5,2 29 6,1,0.0,4.0,98.0,1998.0,NaN,1177.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,18.0,18.0,3.0,3.0,3.0,3.0,2.0,998.0,2.0,10.0,25.0,0.0,3.0,3000.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,102.0,11.0,25.0,1.0,108.0,11.0,25.0,2007
6,2 39 1,1,1.0,1.0,4.0,1997.0,NaN,1168.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,24.0,24.0,2.0,2.0,1.0,1.0,2.0,203.0,6.0,1.0,11.0,0.0,3.0,3700.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,5.0,1.0,NaN,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2007
7,2 54 1,1,2.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,12.0,12.0,8.0,8.0,2.0,2.0,2.0,205.0,3.0,5.0,11.0,0.0,3.0,3200.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,101.0,13.0,11.0,1.0,101.0,13.0,11.0,2007
8,2 89 2,1,0.0,5.0,1.0,2000.0,NaN,1201.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,6.0,6.0,1.0,1.0,2.0,2.0,1.0,NaN,1.0,7.0,21.0,0.0,2.0,3500.0,2.0,0.0,0.0,0.0,101.0,NaN,NaN,1.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,90.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,106.0,11.0,21.0,1.0,101.0,11.0,21.0,2007
9,2 99 2,1,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,14.0,14.0,7.0,7.0,1.0,1.0,2.0,207.0,5.0,8.0,25.0,0.0,3.0,3600.0,1.0,0.0,0.0,0.0,101.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,10.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,104.0,12.0,25.0,1.0,102.0,12.0,25.0,2007

In [4]:
from mnp.configs.rec41 import config_f3

# 4. Limpiar Fase 3 (Estandarización de Etiquetas)
df_clean = apply_standard_labels(df_clean, val_labels_hist, config_f3)

print(f'[OK] Estandarización de Etiquetas completa.')
df_clean.head(10)

[OK] Estandarización de Etiquetas completa.

,CASEID,MIDX,M1,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E,M2F,M2G,M2H,M2I,M2J,M2K,M2L,M2M,M2N,M3A,M3B,M3C,M3D,M3E,M3F,M3G,M3H,M3I,M3J,M3K,M3L,M3M,M3N,M4,M5,M6,M7,M8,M9,M10,M11,M13,M14,M15,M17,M18,M19,M19A,M27,M28,M29,M34,M35,M36,M38,M39,M42A,M42B,M42C,M42D,M42E,M43,M44,M45,M46,M47,M48,M49A,M49B,M49C,M49D,M49E,M49F,M49G,M49X,M49Z,M51A,M54,M55A,M55B,M55C,M55D,M55E,M55F,M55G,M55H,M55I,M55J,M55K,M55L,M55M,M55N,M55X,M55Z,M57A,M57B,M57C,M57D,M57E,M57F,M57G,M57H,M57I,M57J,M57K,M57L,M57M,M57N,M57O,M57P,M57Q,M57R,M57S,M57T,M57U,M57V,M57X,M60,M61,M62,M63,M64,M65A,M65B,M65C,M65D,M65E,M65F,M65G,M65H,M65I,M65J,M65K,M65L,M65X,M66,M67,M68,M69,M70,M71,M72,M73,year
0,1 10 2,1,0.0,5.0,NaN,NaN,4.0,1210.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,9.0,9.0,12.0,12.0,3.0,3.0,1.0,NaN,3.0,9.0,Hospital MINSA,1.0,3.0,2950.0,1.0,0.0,0.0,0.0,101.0,NaN,NaN,1.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,103.0,11.0,21.0,1.0,NaN,NaN,NaN,2007
1,1 22 2,1,2.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,17.0,17.0,1.0,1.0,3.0,3.0,3.0,NaN,3.0,9.0,Hospital MINSA,0.0,3.0,3100.0,1.0,0.0,0.0,0.0,112.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,0.0,NaN,1.0,18.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,118.0,11.0,21.0,1.0,NaN,NaN,NaN,2007
2,1 34 2,1,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,18.0,18.0,9.0,9.0,1.0,1.0,1.0,NaN,3.0,6.0,Hospital ESSALUD,0.0,3.0,3600.0,2.0,0.0,0.0,0.0,102.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,30.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,1.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,110.0,12.0,22.0,1.0,NaN,NaN,NaN,2007
3,2 9 2,1,3.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,20.0,20.0,1.0,1.0,1.0,1.0,2.0,209.0,1.0,8.0,Su domicilio,0.0,3.0,3300.0,2.0,0.0,0.0,0.0,101.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,0.0,1.0,1.0,1.0,1.0,30.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,100.0,11.0,11.0,1.0,100.0,11.0,11.0,2007
4,2 9 2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,19.0,19.0,96.0,10.0,10.0,10.0,2.0,202.0,NaN,NaN,NaN,0.0,3.0,3300.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007
5,2 29 6,1,0.0,4.0,98.0,1998.0,NaN,1177.0,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,18.0,18.0,3.0,3.0,3.0,3.0,2.0,998.0,2.0,10.0,Puesto de salud MINSA,0.0,3.0,3000.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,102.0,11.0,25.0,1.0,108.0,11.0,25.0,2007
6,2 39 1,1,1.0,1.0,4.0,1997.0,NaN,1168.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,24.0,24.0,2.0,2.0,1.0,1.0,2.0,203.0,6.0,1.0,Su domicilio,0.0,3.0,3700.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,5.0,1.0,NaN,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2007
7,2 54 1,1,2.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,12.0,12.0,8.0,8.0,2.0,2.0,2.0,205.0,3.0,5.0,Su domicilio,0.0,3.0,3200.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,0.0,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,101.0,13.0,11.0,1.0,101.0,13.0,11.0,2007
8,2 89 2,1,0.0,5.0,1.0,2000.0,NaN,1201.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,6.0,6.0,1.0,1.0,2.0,2.0,1.0,NaN,1.0,7.0,Hospital MINSA,0.0,2.0,3500.0,2.0,0.0,0.0,0.0,101.0,NaN,NaN,1.0,4.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,90.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,106.0,11.0,21.0,1.0,101.0,11.0,21.0,2007
9,2 99 2,1,2.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,14.0,14.0,7.0,7.0,1.0,1.0,2.0,207.0,5.0,8.0,Puesto de salud MINSA,0.0,3.0,3600.0,1.0,0.0,0.0,0.0,101.0,NaN,NaN,0.0,3.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,10.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,0.0,0.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,104.0,12.0,25.0,1.0,102.0,12.0,25.0,2007

In [5]:
# 4.5 Revisión de Frecuencias (Auditoría Post-Limpieza)
# Variables objetivo a auditar
vars_to_check = [
    'M13', 'M14', 'M15', 'M17', 'M18', 'M19', 
    'M34', 'M4', 'M5', 'M45', 'M46', 'M54', 'M60', 'M70', 'M55A'
]

print("=== AUDITORÍA DE FRECUENCIAS (Con Nulos) ===")
for col in vars_to_check:
    if col in df_clean.columns:
        print(f"\n--- {col} ---")
        print(df_clean[col].value_counts(dropna=False).head(10)) # Mostramos el top 10

=== AUDITORÍA DE FRECUENCIAS (Con Nulos) ===

--- M13 ---
M13
2.0    72054
1.0    63287
3.0    57226
NaN    46405
4.0    25098
5.0    13822
6.0     8426
7.0     3613
8.0     1482
0.0     1159
Name: count, dtype: int64

--- M14 ---
M14
NaN     42850
10.0    35660
9.0     34887
8.0     31200
12.0    25652
7.0     24653
6.0     21056
11.0    19822
5.0     13393
13.0    10126
Name: count, dtype: int64

--- M15 ---
M15
Hospital MINSA                129117
Centro de salud MINSA          50354
Hospital ESSALUD               41929
Su domicilio                   28651
Clínica privada                20752
Puesto de salud MINSA           9911
NaN                             4649
Otro                            3210
Consultorio médico privado      1284
Center/Posta ESSALUD            1113
Name: count, dtype: int64

--- M17 ---
M17
0.0    209701
1.0     83115
NaN         8
Name: count, dtype: int64

--- M18 ---
M18
3.0    149357
2.0     72515
4.0     57049
5.0      8840
1.0      4838
NaN       225
Name: count, dtype: int64

--- M19 ---
M19
NaN       17764
3000.0    14511
3500.0    14169
3200.0    12528
3800.0    11657
2800.0    11360
3300.0     8266
3600.0     8026
3400.0     7642
3100.0     6611
Name: count, dtype: int64

--- M34 ---
M34
0.0      159030
101.0     31464
102.0     25103
103.0     14782
104.0      9535
105.0      6867
201.0      6067
106.0      5247
202.0      3707
108.0      3389
Name: count, dtype: int64

--- M4 ---
M4
NaN     105284
24.0     28861
12.0     25999
18.0     23956
14.0     10226
15.0      9797
20.0      8826
6.0       5864
0.0       5837
16.0      5510
Name: count, dtype: int64

--- M5 ---
M5
24.0    30594
12.0    30347
18.0    27070
14.0    14256
15.0    13613
20.0    11540
6.0     10454
8.0      9454
16.0     9058
9.0      8979
Name: count, dtype: int64

--- M45 ---
M45
1.0    224327
NaN     42384
0.0     26113
Name: count, dtype: int64

--- M46 ---
M46
NaN      69070
90.0     27628
30.0     25364
60.0     22643
120.0    20959
180.0    20670
150.0    18933
210.0    13591
240.0     8890
100.0     4286
Name: count, dtype: int64

--- M54 ---
M54
0.0    208227
NaN     49816
1.0     34781
Name: count, dtype: int64

--- M60 ---
M60
0.0    233511
NaN     49175
1.0     10138
Name: count, dtype: int64

--- M70 ---
M70
1.0    243650
NaN     44898
0.0      4276
Name: count, dtype: int64

--- M55A ---
M55A
0.0    285259
1.0      4502
NaN      3063
Name: count, dtype: int64

In [6]:
# 4.8 Filtrado estricto de variables (Selección del Diccionario)
cols_to_keep = [
    'CASEID', 'MIDX', 'year', # Llaves maestras
    'M13', 'M14', 'M15', 'M17', 'M18', 'M19', 'M34', 'M4', 'M5', 
    'M45', 'M46', 'M54', 'M60', 'M70', 
    'M55A', 'M55B', 'M55C', 'M55E', 'M55F', 'M55G', 'M55H', 'M55I', 'M55X', 'M55Z'
]

# Quedarnos solo con las variables aprobadas
df_clean = df_clean[[c for c in cols_to_keep if c in df_clean.columns]]

print(f"Dataset podado a {df_clean.shape[1]} variables doradas. Shape: {df_clean.shape}")

Dataset podado a 27 variables doradas. Shape: (292824, 27)

In [7]:
# 5. Guardar Parquet
output_path = "/Users/abelguevarah/Desktop/invs/malnutrition-research/data/interim/v1/rec41_cleaned.parquet"
df_clean.to_parquet(output_path, index=False)
print(f"[OK] Guardado en: {output_path}")

[OK] Guardado en: /Users/abelguevarah/Desktop/invs/malnutrition-research/data/interim/v1/rec41_cleaned.parquet