In [1]:
import pandas as pd
import numpy as np
import gc
from IPython.display import display
from mnp.ingestion.loader import load_endes
from mnp.utils.profiler import centrar_notebook
from mnp.utils.cleaning import run_phase1_engine
# Configuración visual
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
centrar_notebook()

print("[OK]")

2026-06-14 12:45:38.804 | INFO     | mnp.config:<module>:11 - PROJ_ROOT path is: /Users/abelguevarah/Desktop/invs/malnutrition-research

[OK]

In [2]:
# Carga de datos
history = load_endes(
        year=range(2007, 2025),
        module="housing",
        record="rech23h",
        meta=True
    )

dfs = []
col_labels_hist = {}
val_labels_hist = {}

for year in sorted(list(history.keys())):
    year_df, year_meta = history.pop(year)
    col_labels_hist[year] = year_meta.column_names_to_labels
    val_labels_hist[year] = year_meta.variable_value_labels
    
    dfs.append(year_df.assign(year=year))

df_raw = pd.concat(dfs, ignore_index=True)
del dfs
gc.collect()

print(f"[OK] Data RECH23 cargada: {len(df_raw)} filas y {df_raw.shape[1]} columnas.")
print(f"[OK] Diccionario cargado: {len(col_labels_hist)} Column Labels, {len(val_labels_hist)} Value Labels")

2026-06-14 12:45:40.288 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:41.100 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:42.018 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:42.808 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:43.580 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.sav desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:44.396 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.sav desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:45.189 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:46.004 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:46.844 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:47.920 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:48.848 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:49.794 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:50.751 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo65 [Alias: rech23h]
2026-06-14 12:45:51.761 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.sav desde Modulo1630 [Alias: rech23h]
2026-06-14 12:45:52.733 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.SAV desde Modulo1630 [Alias: rech23h]
2026-06-14 12:45:53.669 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23.sav desde Modulo1630 [Alias: rech23h]
2026-06-14 12:45:54.615 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23_2023.sav desde Modulo1630 [Alias: rech23h]
2026-06-14 12:45:55.628 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH23_2024.sav desde Modulo1630 [Alias: rech23h]
2026-06-14 12:45:56.734 | SUCCESS  | mnp.ingestion.loader:_load_multiple_years:290 - ✅ ¡Historia cargada y organizada por años!
[OK] Data RECH23 cargada: 607287 filas y 253 columnas.
[OK] Diccionario cargado: 18 Column Labels, 18 Value Labels

In [3]:
# Inspeccionar variable
print(df_raw['SH107'].value_counts(dropna=False))
print(df_raw['SH124'].value_counts(dropna=False))
print(df_raw['SH224'].value_counts(dropna=False))
print(df_raw['HV234'].value_counts(dropna=False))

SH107
NaN    580453
4.0     15261
3.0      6745
2.0      1829
5.0      1681
9.0       702
1.0       616
Name: count, dtype: int64
SH124
NaN    580682
4.0     16432
3.0      4802
5.0      1998
2.0      1891
1.0       802
9.0       680
Name: count, dtype: int64
SH224
4.0    225521
NaN    163628
9.0    111852
3.0     53276
2.0     22299
1.0     16697
5.0     14014
Name: count, dtype: int64
HV234
30.0     241953
994.0    114213
NaN      110891
15.0      64823
995.0     31273
7.0       26019
0.0       18115
Name: count, dtype: int64

In [4]:
# Inspeccionar variable
print(df_raw['SHSEMES'].value_counts(dropna=False))
print(df_raw['SHTRIMES'].value_counts(dropna=False))

SHSEMES
2.0    272128
1.0    270789
NaN     64370
Name: count, dtype: int64
SHTRIMES
NaN     542917
22.0      8065
11.0      5138
4.0       4966
9.0       4958
8.0       4923
10.0      4913
7.0       4900
5.0       4637
12.0      4631
6.0       4458
21.0      3737
3.0       2293
2.0       2200
1.0       1884
14.0      1586
13.0      1081
Name: count, dtype: int64

In [5]:
df_raw.head(10)

,HHID,HV201,HV202,HV204,HV205,HV206,HV207,HV208,HV209,HV210,HV211,HV212,HV213,HV214,HV215,HV216,HV217,HV218,HV219,HV220,HV221,HV225,HV226,HV227,HV228,HV234,HV235,HV236,HV237,HV237A,HV237B,HV237C,HV237D,HV237E,HV237F,HV237G,HV237H,HV237I,HV237J,HV237K,HV237X,HV237Z,HV238,HV239,HV240,HV241,HV242,HV243A,HV243B,HV243C,HV243D,HV244,HV245,HV246,HV246A,HV246B,HV246C,HV246D,HV246E,HV246F,HV246G,HV246H,HV246I,HV246J,HV246K,HV247,HV248,HV249,HV250,HV251,HV270,HV271,HML1,HML1A,HML2,SHVER,SHREGION,SHTRIMES,SHPROVIN,SHDISTRI,SHTOTH,SHEQUIPO,SH2201,SH2202,SH2203,SH2204,SH2208,SH2209,SH2210,SH2211,SH2212A,SH2212B,SH2212C,SH2212D,SH2212E,SH2212F,SH2213,SH2401,SH2406,SH2407,SH2408,SH2409,SH2410,SH2412,SH2413,SH2414,SH25F,SH25H,SH26A,SH2601,SH2602,SH2604,SH2605,SH2606,SH2607,SH2609,SH27CA,SH27CB,SH27CC,SH27CD,SH27CE,SH28BB,SH2801,SH2802,SH2803,SH28D,SH28EE,SH01H,SH01M,SH31H,SH31M,year,SHSEMES,SH32,SH33,SH37,SH39,SH40,SH41,SH42,SH46,SH48,SH49,SH50,SH51A,SH51B,SH51C,SH51D,SH51E,SH51J,SH51K,SH51L,SH51M,SH51N,SH51O,SH51P,SH51Q,SH51R,SH51S,SH53,SH54,SH56,SH59,SH60,SH61,SH62,SH63,SH67A,SH67B,SH67C,SH67D,SH67E,SH68F,SH69,SH70,SH107,SH108U,SH108,SH110,SH81H,SH81M,SH43,SH51,SH52,SH58,SH61A,SH61B,SH61C,SH61D,SH61E,SH61J,SH61K,SH61L,SH61M,SH61N,SH61O,SH61P,SH61Q,SH61R,SH61S,SH64,SH66,SH71,SH72,SH73,SH77A,SH77B,SH77C,SH77D,SH77E,SH78F,SH79,SH80,SH124,SH125U,SH125,SH127,SH90H,SH90M,SHWLTHI2,SHWLTHF2,SXH73,SH76A,SH76B,SH76C,SH76D,SH76E,SH77F,SH78,SH224,SH225U,SH225,SH227,SH82H,SH82M,QH90,QH90A,QH91D,QH91M,QH91Y,QH93,QH94A,QH94AB,QH94B,QH94BB,QH94C,QH94CB,QH94D,hv271,hv270,QH227A,QH227B,ID1
0,1 4,11.0,11.0,996.0,31.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,11.0,21.0,34.0,1.0,3.0,1.0,2.0,65.0,0.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.0,2.0,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,2.0,-43677.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 10,11.0,11.0,996.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,1.0,4.0,1.0,1.0,26.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,1.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,32939.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,10.0,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,11.0,11.0,996.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,2.0,4.0,1.0,1.0,64.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.0,NaN,NaN,1.0,1.0,1.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,41740.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,8.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,11.0,11.0,996.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,2.0,4.0,1.0,1.0,38.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,NaN,1.0,1.0,0.0,NaN,0.0,0.0,0.0,NaN,1.0,6.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,41740.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 34,11.0,11.0,996.0,11.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,34.0,21.0,34.0,2.0,2.0,1.0,1.0,33.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,4.0,86784.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 40,11.0,11.0,996.0,11.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,11.0,21.0,34.0,1.0,1.0,1.0,2.0,60.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,0.0,0.0,1.0,3.0,1.0,1.0,NaN,0.0,2.0,2.0,NaN,0.0,6.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,2694.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,30.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 46,11.0,11.0,996.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,11.0,21.0,34.0,1.0,4.0,1.0,1.0,42.0,1.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.0,1.0,1.0,0.0,NaN,0.0,0.0,1.0,12.0,1.0,0.0,NaN,2.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,6178.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,120.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1 52,11.0,11.0,996.0,11.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,34.0,21.0,34.0,2.0,2.0,1.0,1.0,38.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,0.0,0.0,1.0,0.0,1.0,0.0,NaN,0.0,0.0,0.0,NaN,4.0,4.0,4.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,4.0,98292.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,3.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 58,11.0,11.0,996.0,11.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,34.0,31.0,34.0,5.0,4.0,1.0,1.0,59.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,0.0,0.0,1.0,6.0,1.0,0.0,NaN,1.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,5.0,166023.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,60.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 64,11.0,11.0,996.0,11.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,2.0,3.0,1.0,2.0,71.0,0.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,NaN,1.0,0.0,NaN,0.0,0.0,0.0,NaN,5.0,2.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,3.0,4924.0,NaN,NaN,NaN,2.0,3.0,4.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import numpy as np
from mnp.utils.cleaning import run_phase1_engine
from mnp.configs.rech23 import config_f1

# --- 1. CURA MASIVA PARA EL DICCIONARIO CORRUPTO DE YODO ---
# Convertimos las categorías 1-4 a PPM puros.
# El 5 y 9 se van a la zona de purga (995 y 994) para que Fase 1 los vuelva NaN.
diccionario_yodo = {
    1.0: 0.0, 2.0: 7.0, 3.0: 15.0, 4.0: 30.0,
    5.0: 995.0, 9.0: 994.0
}
columnas_yodo = ['SH107', 'SH124', 'SH224']
for col in columnas_yodo:
    if col in df_raw.columns:
        df_raw[col] = df_raw[col].replace(diccionario_yodo)


# --- 2. SPLITS MANUALES POR COLUMNAS RECICLADAS DEL INEI ---
# Agua y Basura
df_raw['SH42_Agua_Todo_El_Dia'] = np.where(df_raw['year'] >= 2010, df_raw['SH42'], np.nan)
df_raw['SH48_Conserva_Agua'] = np.where(df_raw['year'] >= 2010, df_raw['SH48'], np.nan)
df_raw['SH48_Basura'] = np.where(df_raw['year'] == 2009, df_raw['SH48'], np.nan)

# Limpieza, Basura y Luz (SH60)
df_raw['SH56_Frec_Limpieza'] = np.where(df_raw['year'] >= 2010, df_raw['SH56'], np.nan)
df_raw['SH56_Limpió_Baño'] = np.where(df_raw['year'] == 2009, df_raw['SH56'], np.nan)
df_raw['SH59_Frec_Recojo'] = np.where(df_raw['year'] >= 2010, df_raw['SH59'], np.nan)
df_raw['SH59_Recogen_Basura'] = np.where(df_raw['year'] == 2009, df_raw['SH59'], np.nan)
df_raw['SH60_Tipo_Basurero'] = np.where(df_raw['year'] >= 2010, df_raw['SH60'], np.nan)
df_raw['SH60_Fuente_Luz'] = np.where(df_raw['year'] == 2009, df_raw['SH60'], np.nan)

# Split de Luz y Hectáreas (SH70)
df_raw['SH70_Fuente_Luz'] = np.where(df_raw['year'] >= 2010, df_raw['SH70'], np.nan)
df_raw['SH70_Hectareas'] = np.where(df_raw['year'] == 2009, df_raw['SH70'], np.nan)


# Drop
df_raw = df_raw.drop(columns=['SH42', 'SH48', 'SH56', 'SH59', 'SH60', 'SH70'])

df_clean = run_phase1_engine(df_raw, config_f1)

print(f'[OK] Limpieza biológica completa. Shape: {df_clean.shape}')
df_clean.head(5)

/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH42_Agua_Todo_El_Dia'] = np.where(df_raw['year'] >= 2010, df_raw['SH42'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH48_Conserva_Agua'] = np.where(df_raw['year'] >= 2010, df_raw['SH48'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH48_Basura'] = np.where(df_raw['year'] == 2009, df_raw['SH48'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH56_Frec_Limpieza'] = np.where(df_raw['year'] >= 2010, df_raw['SH56'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH56_Limpió_Baño'] = np.where(df_raw['year'] == 2009, df_raw['SH56'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH59_Frec_Recojo'] = np.where(df_raw['year'] >= 2010, df_raw['SH59'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH59_Recogen_Basura'] = np.where(df_raw['year'] == 2009, df_raw['SH59'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH60_Tipo_Basurero'] = np.where(df_raw['year'] >= 2010, df_raw['SH60'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:30: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH60_Fuente_Luz'] = np.where(df_raw['year'] == 2009, df_raw['SH60'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH70_Fuente_Luz'] = np.where(df_raw['year'] >= 2010, df_raw['SH70'], np.nan)
/var/folders/jl/cmchwwpd2814r_jhdlf_y37w0000gn/T/ipykernel_27183/1458634928.py:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_raw['SH70_Hectareas'] = np.where(df_raw['year'] == 2009, df_raw['SH70'], np.nan)

[Limpieza] Iniciando Motor Fase 1...
[Limpieza] Eliminando 102 columnas (Optimización RAM)...
[Limpieza] Drops iniciales completados en 0.08s
[Limpieza] Casteando 1 columnas clave...
[Limpieza] Casteo completado en 0.25s
[Limpieza] Limpiando falsos numéricos...
[Limpieza] Falsos numéricos limpiados en 0.20s
[Limpieza] Aplicando reemplazos custom...
[Limpieza] Reemplazos custom completados en 0.02s
[Limpieza] Escalamiento matemático (x/100,000)...
[Limpieza] Escalamiento /100k completado en 0.00s
[Limpieza] Ejecutando Coalesce (Unificación de columnas)...

/Users/abelguevarah/Desktop/invs/malnutrition-research/mnp/utils/cleaning.py:119: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_out[target_col] = res
/Users/abelguevarah/Desktop/invs/malnutrition-research/mnp/utils/cleaning.py:119: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_out[target_col] = res
/Users/abelguevarah/Desktop/invs/malnutrition-research/mnp/utils/cleaning.py:119: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_out[target_col] = res
/Users/abelguevarah/Desktop/invs/malnutrition-research/mnp/utils/cleaning.py:119: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_out[target_col] = res
/Users/abelguevarah/Desktop/invs/malnutrition-research/mnp/utils/cleaning.py:119: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_out[target_col] = res

[Limpieza] Coalesce completado en 0.57s
[Limpieza] Motor Fase 1 finalizado. Tiempo total: 1.12s
[OK] Limpieza biológica completa. Shape: (607287, 93)

,HHID,HV201,HV204,HV205,HV206,HV207,HV208,HV209,HV210,HV211,HV212,HV213,HV214,HV215,HV216,HV217,HV218,HV219,HV220,HV221,HV225,HV226,HV234,HV236,HV237,HV237A,HV237B,HV237C,HV237D,HV237E,HV237F,HV237G,HV237X,HV242,HV243A,HV243B,HV243C,HV243D,HV244,HV246,HV270,HV271,SHREGION,SHPROVIN,SHDISTRI,SHTOTH,year,SHSEMES,SH49,SH50,SH63,SH43,SH51,SH52,SH58,SH61A,SH61B,SH61C,SH61D,SH61E,SH61J,SH61K,SH61L,SH61M,SH61N,SH61O,SH61P,SH61Q,SH61R,SH61S,SH64,SH71,SH76B,SH76C,SH76D,SH77F,SH227,QH227A,QH227B,ID1,SH42_Agua_Todo_El_Dia,SH48_Conserva_Agua,SH48_Basura,SH56_Frec_Limpieza,SH56_Limpió_Baño,SH59_Recogen_Basura,SH70_Fuente_Luz,SH51_Pago_Agua,SH52_Institucion_Agua,SH51_Frec_Pago_Agua,SH49_Frec_Basura,SH50_Tipo_Basurero,HV240
0,1 4,11.0,0.0,31.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,11.0,21.0,34.0,1.0,3.0,1.0,2.0,65.0,0.0,NaN,8.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,2.0,-0.43677,3.0,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,1 10,11.0,0.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,1.0,4.0,1.0,1.0,26.0,0.0,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,3.0,0.32939,3.0,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,11.0,0.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,2.0,4.0,1.0,1.0,64.0,0.0,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,1.0,NaN,0.0,0.0,0.0,0.0,3.0,0.41740,3.0,1.0,1.0,3.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,11.0,0.0,11.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,34.0,21.0,34.0,2.0,4.0,1.0,1.0,38.0,0.0,1.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0,NaN,0.0,0.0,0.0,1.0,3.0,0.41740,3.0,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 34,11.0,0.0,11.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,34.0,21.0,34.0,2.0,2.0,1.0,1.0,33.0,0.0,0.0,2.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,4.0,0.86784,3.0,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,3.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
from importlib import reload
import mnp.utils.cleaning
reload(mnp.utils.cleaning)
from mnp.utils.cleaning import apply_standard_labels
from mnp.configs.rech23 import config_f1, config_f3

# 1. El motor estandariza todas las variables normales leyendo config_f3
df_final = apply_standard_labels(df_clean, val_labels_hist, config_f3, config_f1)

# 2. Mapeos manuales EXCLUSIVOS para las columnas del Split (que el diccionario no reconoce)
dict_binario = {1.0: "Sí", 2.0: "No", 0.0: "No"}
columnas_manuales = [
    'SH42_Agua_Todo_El_Dia', 
    'SH48_Conserva_Agua', 
    'SH56_Limpió_Baño', 
    'SH59_Recogen_Basura'
]

for col in columnas_manuales:
    if col in df_final.columns:
        df_final[col] = df_final[col].map(dict_binario)

print(f"[OK] (Estandarización de Etiquetas) completada.")
df_final.head(15)

[OK] (Estandarización de Etiquetas) completada.

,HHID,HV201,HV204,HV205,HV206,HV207,HV208,HV209,HV210,HV211,HV212,HV213,HV214,HV215,HV216,HV217,HV218,HV219,HV220,HV221,HV225,HV226,HV234,HV236,HV237,HV237A,HV237B,HV237C,HV237D,HV237E,HV237F,HV237G,HV237X,HV242,HV243A,HV243B,HV243C,HV243D,HV244,HV246,HV270,HV271,SHREGION,SHPROVIN,SHDISTRI,SHTOTH,year,SHSEMES,SH49,SH50,SH63,SH43,SH51,SH52,SH58,SH61A,SH61B,SH61C,SH61D,SH61E,SH61J,SH61K,SH61L,SH61M,SH61N,SH61O,SH61P,SH61Q,SH61R,SH61S,SH64,SH71,SH76B,SH76C,SH76D,SH77F,SH227,QH227A,QH227B,ID1,SH42_Agua_Todo_El_Dia,SH48_Conserva_Agua,SH48_Basura,SH56_Frec_Limpieza,SH56_Limpió_Baño,SH59_Recogen_Basura,SH70_Fuente_Luz,SH51_Pago_Agua,SH52_Institucion_Agua,SH51_Frec_Pago_Agua,SH49_Frec_Basura,SH50_Tipo_Basurero,HV240
0,1 4,Red dentro de vivienda,0.0,"Río, acequia o canal",Si,Si,Si,No,No,No,No,Tierra / arena,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,"Dos adultos, mismo sexo",1.0,Femenino,65.0,No,NaN,Madera,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,NaN,No,NaN,No,No,No,No,2.0,-0.43677,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,3.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,1 10,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,más de 3 adultos relacionados,1.0,Masculino,26.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,No,No,NaN,No,No,Si,No,3.0,0.32939,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,1.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 16,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,más de 3 adultos relacionados,1.0,Masculino,64.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,Si,NaN,No,No,No,No,3.0,0.41740,Sierra,1.0,1.0,3.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 22,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,más de 3 adultos relacionados,1.0,Masculino,38.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,No,Si,3.0,0.41740,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 34,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,Si,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,"Dos adultos, dif. Sexo",1.0,Masculino,33.0,No,No,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,No,No,4.0,0.86784,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Si,No,NaN,NaN,NaN,3.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 40,Red dentro de vivienda,0.0,Dentro de la vivienda,No,Si,Si,No,No,No,No,Tierra / arena,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,Un adulto,1.0,Femenino,60.0,No,No,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,Si,Si,3.0,0.02694,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,No,Si,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 46,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Tierra / arena,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,más de 3 adultos relacionados,1.0,Masculino,42.0,Si,No,Madera,NaN,NaN,No,No,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,Si,Si,3.0,0.06178,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
7,1 52,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,Si,Si,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,"Dos adultos, dif. Sexo",1.0,Masculino,38.0,Si,No,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,Si,NaN,No,No,Si,Si,4.0,0.98292,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 58,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,Si,No,No,No,Cemento / ladrillo,Ladrillo o bloques de cemento,"Plancha de calamina, fibra de cemento o similares",5.0,más de 3 adultos relacionados,1.0,Masculino,59.0,Si,No,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,Si,Si,5.0,1.66023,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Si,No,NaN,NaN,NaN,7.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 64,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,No,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,"Dos adultos, mismo sexo",1.0,Femenino,71.0,No,No,Madera,NaN,NaN,No,No,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,No,Si,3.0,0.04924,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
10,1 81,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",2.0,"Dos adultos, dif. Sexo",1.0,Femenino,42.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,NaN,No,NaN,No,No,No,No,3.0,0.48118,Sierra,1.0,1.0,2.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,3.0,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1 87,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,Un adulto,1.0,Femenino,17.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,NaN,No,NaN,No,No,No,No,3.0,0.40206,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,1.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1 93,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",1.0,"Dos adultos, dif. Sexo",1.0,Femenino,83.0,No,Si,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,No,No,3.0,0.37652,Sierra,1.0,1.0,2.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,2.0,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1 99,Red dentro de vivienda,0.0,Latrina (pozo ciego o negro),Si,Si,Si,No,No,No,No,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",3.0,más de 3 adultos relacionados,1.0,Masculino,76.0,No,Si,Madera,NaN,NaN,No,No,No,No,No,No,No,NaN,No,Si,No,NaN,No,No,Si,Si,3.0,0.01961,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,3.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
14,1105,Red dentro de vivienda,0.0,Dentro de la vivienda,Si,Si,Si,No,Si,No,Si,Cemento / ladrillo,Adobe o tapia,"Plancha de calamina, fibra de cemento o similares",3.0,más de 3 adultos relacionados,1.0,Masculino,49.0,No,No,LPG,NaN,NaN,Si,Si,No,No,No,No,No,NaN,No,NaN,No,NaN,No,No,No,No,4.0,0.85646,Sierra,1.0,1.0,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,4.0,Si,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
from mnp.config import INTERIM_DATA_DIR
import os
# Aseguramos que la carpeta interim exista
os.makedirs(INTERIM_DATA_DIR, exist_ok=True)
# Ruta del archivo final
output_path = INTERIM_DATA_DIR / "rech23_cleaned.parquet"
# Guardamos en formato parquet (preserva tipos de datos y ahorra RAM)
df_final.to_parquet(output_path, index=False)
print(f"[OK] Datos RECH23 guardados exitosamente en:")
print(f"-> {output_path}")

[OK] Datos RECH23 guardados exitosamente en:
-> /Users/abelguevarah/Desktop/invs/malnutrition-research/data/interim/rech23_cleaned.parquet

In [ ]:
import sweetviz as sv
from mnp.configs.column_labels import SWEETVIZ_LABELS
from mnp.config import INTERIM_DATA_DIR  # Importamos tu variable mágica

df_sweetviz = df_final.rename(columns=SWEETVIZ_LABELS)
reporte_sv = sv.analyze(df_sweetviz)

# Usamos la ruta absoluta inteligente y la pasamos a string
ruta_reporte = str(INTERIM_DATA_DIR / 'rech23_sweetviz_report.html')

reporte_sv.show_html(ruta_reporte)
reporte_sv.show_notebook(w="100%", h="800", filepath=ruta_reporte)

In [ ]:
df_final['HV270'].value_counts(dropna=False)