In [1]:
import pandas as pd
import numpy as np
import gc
from IPython.display import display
from mnp.ingestion.loader import load_endes
from mnp.utils.profiler import centrar_notebook
from mnp.utils.cleaning import run_phase1_engine
# Configuración visual
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
centrar_notebook()

print("[OK]")

2026-06-10 22:04:38.402 | INFO     | mnp.config:<module>:11 - PROJ_ROOT path is: /Users/abelguevarah/Desktop/invs/malnutrition-research

[OK]

In [2]:
# Carga de datos
history = load_endes(
        year=range(2007, 2025),
        module="household",
        record="household_roster",
        meta=True
    )

dfs = []
col_labels_hist = {}
val_labels_hist = {}

for year in sorted(list(history.keys())):
    year_df, year_meta = history.pop(year)
    col_labels_hist[year] = year_meta.column_names_to_labels
    val_labels_hist[year] = year_meta.variable_value_labels
    
    dfs.append(year_df.assign(year=year))

df_raw = pd.concat(dfs, ignore_index=True)
del dfs
gc.collect()

print(f"[OK] Data RECH6 cargada: {len(df_raw)} filas y {df_raw.shape[1]} columnas.")
print(f"[OK] Diccionario cargado: {len(col_labels_hist)} Column Labels, {len(val_labels_hist)} Value Labels")

2026-06-10 22:04:38.534 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:39.271 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:40.326 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:40.905 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:41.498 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.sav desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:42.116 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.sav desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:42.678 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:43.378 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:44.102 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:45.103 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:46.035 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:46.960 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:47.850 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.sav desde Modulo64 [Alias: household_roster]
2026-06-10 22:04:48.781 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.sav desde Modulo1629 [Alias: household_roster]
2026-06-10 22:04:49.667 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.SAV desde Modulo1629 [Alias: household_roster]
2026-06-10 22:04:50.558 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1.sav desde Modulo1629 [Alias: household_roster]
2026-06-10 22:04:51.554 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1_2023.sav desde Modulo1629 [Alias: household_roster]
2026-06-10 22:04:52.445 | INFO     | mnp.ingestion.loader:load_endes:375 - ✓ Cargando registro: RECH1_2024.sav desde Modulo1629 [Alias: household_roster]
2026-06-10 22:04:53.317 | SUCCESS  | mnp.ingestion.loader:_load_multiple_years:290 - ✅ ¡Historia cargada y organizada por años!
[OK] Data RECH6 cargada: 2291232 filas y 59 columnas.
[OK] Diccionario cargado: 18 Column Labels, 18 Value Labels

In [3]:
# Inspeccionar variable
# df_raw['HC51'].value_counts(dropna=False)
df_raw.head(10)

,HHID,HVIDX,HV101,HV102,HV103,HV104,HV105,HV106,HV107,HV108,HV109,HV110,HV111,HV112,HV113,HV114,HV115,HV116,HV117,HV118,HV120,HV121,HV122,HV123,HV124,HV125,HV126,HV127,HV128,HV129,HV130,HV131,HV132,HV133,HV134,HV135,HV136,HV137,HV138,HV139,HV140,year,QH21A,QH21B,QH13A1,QH13A2,QH13A3,QH13A4,QH13A5,QH13A6A,QH13A6B,QH13A6C,QH13A6D,QH13A6,QH25A,QH25B,QH25CM,QH25CA,ID1
0,1 4,1.0,1.0,1.0,1.0,2.0,65.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 4,2.0,3.0,1.0,1.0,2.0,39.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 4,3.0,5.0,1.0,1.0,1.0,11.0,2.0,0.0,6.0,3.0,1.0,1.0,2.0,1.0,0.0,NaN,NaN,0.0,NaN,0.0,1.0,2.0,1.0,7.0,1.0,1.0,6.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 10,1.0,1.0,1.0,0.0,1.0,26.0,2.0,5.0,11.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 10,2.0,2.0,1.0,1.0,2.0,20.0,2.0,5.0,11.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 10,3.0,3.0,1.0,1.0,2.0,1.0,0.0,NaN,0.0,0.0,0.0,1.0,2.0,1.0,1.0,NaN,NaN,0.0,NaN,1.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 10,4.0,10.0,1.0,0.0,2.0,51.0,1.0,4.0,4.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1 16,1.0,1.0,1.0,1.0,1.0,64.0,1.0,5.0,5.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 16,2.0,2.0,1.0,1.0,2.0,35.0,1.0,2.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 16,3.0,11.0,1.0,1.0,2.0,16.0,2.0,1.0,7.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,NaN,0.0,1.0,2.0,1.0,7.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
from mnp.utils.cleaning import run_phase1_engine
from mnp.configs.rech1 import config_f1

# 3. Limpiar
df_clean = run_phase1_engine(df_raw, config_f1)

print(f'[OK] Limpieza biológica completa. Shape: {df_clean.shape}')
df_clean.head(5)

[Limpieza] Iniciando Motor Fase 1...
[Limpieza] Eliminando 28 columnas (Optimización RAM)...
[Limpieza] Drops iniciales completados en 0.27s
[Limpieza] Casteando 2 columnas clave...
[Limpieza] Casteo completado en 3.01s
[Limpieza] Limpiando falsos numéricos...
[Limpieza] Falsos numéricos limpiados en 0.21s
[Limpieza] Escalamiento matemático (x/1,000,000)...
[Limpieza] Escalamiento /1M completado en 0.00s
[Limpieza] Ejecutando Coalesce (Unificación de columnas)...
[Limpieza] Coalesce completado en 0.00s
[Limpieza] Motor Fase 1 finalizado. Tiempo total: 3.49s
[OK] Limpieza biológica completa. Shape: (2291232, 31)

,HHID,HVIDX,HV101,HV102,HV103,HV104,HV105,HV106,HV107,HV108,HV109,HV110,HV111,HV112,HV113,HV114,HV115,HV117,HV118,HV120,HV121,HV122,HV124,HV125,HV126,HV128,year,QH13A6A,QH13A6B,QH13A6C,QH13A6D
0,1 4,1,1.0,1.0,1.0,2.0,65.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007,NaN,NaN,NaN,NaN
1,1 4,2,3.0,1.0,1.0,2.0,39.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007,NaN,NaN,NaN,NaN
2,1 4,3,5.0,1.0,1.0,1.0,11.0,2.0,0.0,6.0,3.0,1.0,1.0,2.0,1.0,NaN,NaN,0.0,NaN,0.0,1.0,2.0,7.0,1.0,1.0,6.0,2007,NaN,NaN,NaN,NaN
3,1 10,1,1.0,1.0,0.0,1.0,26.0,2.0,5.0,11.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007,NaN,NaN,NaN,NaN
4,1 10,2,2.0,1.0,1.0,2.0,20.0,2.0,5.0,11.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007,NaN,NaN,NaN,NaN

In [5]:
from importlib import reload
import mnp.utils.cleaning
reload(mnp.utils.cleaning)
from mnp.utils.cleaning import apply_standard_labels
from mnp.configs.rech1 import config_f1, config_f3
# Le pasamos config_f1 para que el motor sepa mágicamente dónde buscar 
# gracias a tus propias reglas de Coalesce.
df_final = apply_standard_labels(df_clean, val_labels_hist, config_f3, config_f1)
print(f"[OK] Fase 3 (Estandarización de Etiquetas) completada.")
df_final.head(15)

[OK] Fase 3 (Estandarización de Etiquetas) completada.

,HHID,HVIDX,HV101,HV102,HV103,HV104,HV105,HV106,HV107,HV108,HV109,HV110,HV111,HV112,HV113,HV114,HV115,HV117,HV118,HV120,HV121,HV122,HV124,HV125,HV126,HV128,year,QH13A6A,QH13A6B,QH13A6C,QH13A6D
0,1 4,1,Jefe del Hogar,Sí,Sí,Mujer,65.0,Primario,0.0,0.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
1,1 4,2,Hijo/Hija,Sí,Sí,Mujer,39.0,Primario,0.0,0.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
2,1 4,3,Nieto,Sí,Sí,Hombre,11.0,Secundario,0.0,6.0,Secundaria incompleta,Sí,Sí,2.0,Sí,NaN,NaN,0.0,NaN,No elegible,Actualmente asistiendo,Secundario,7.0,Sí,Primario,6.0,2007,NaN,NaN,NaN,NaN
3,1 10,1,Jefe del Hogar,Sí,No,Hombre,26.0,Secundario,5.0,11.0,Secundaria completa,No,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
4,1 10,2,Esposa o esposo,Sí,Sí,Mujer,20.0,Secundario,5.0,11.0,Secundaria completa,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
5,1 10,3,Hijo/Hija,Sí,Sí,Mujer,1.0,"Sin educación, preescolar",NaN,0.0,Sin educación,No,Sí,2.0,Sí,1.0,NaN,0.0,NaN,Elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
6,1 10,4,Otro pariente,Sí,No,Mujer,51.0,Primario,4.0,4.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
7,1 16,1,Jefe del Hogar,Sí,Sí,Hombre,64.0,Primario,5.0,5.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
8,1 16,2,Esposa o esposo,Sí,Sí,Mujer,35.0,Primario,2.0,2.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
9,1 16,3,Hijo adoptado,Sí,Sí,Mujer,16.0,Secundario,1.0,7.0,Secundaria incompleta,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,Sí,Secundario,7.0,2007,NaN,NaN,NaN,NaN
10,1 16,4,Hijo adoptado,Sí,Sí,Mujer,13.0,Secundario,0.0,6.0,Secundaria incompleta,Sí,Sí,2.0,Sí,NaN,NaN,0.0,NaN,No elegible,Actualmente asistiendo,Secundario,7.0,Sí,Primario,6.0,2007,NaN,NaN,NaN,NaN
11,1 16,5,Hijo adoptado,Sí,Sí,Hombre,10.0,Primario,5.0,5.0,Primaria incompleta,Sí,Sí,2.0,Sí,NaN,NaN,0.0,NaN,No elegible,Actualmente asistiendo,Primario,6.0,Sí,Primario,5.0,2007,NaN,NaN,NaN,NaN
12,1 22,1,Jefe del Hogar,Sí,Sí,Hombre,38.0,Secundario,5.0,11.0,Secundaria completa,No,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
13,1 22,2,Esposa o esposo,Sí,Sí,Mujer,34.0,Primario,5.0,5.0,Primaria incompleta,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,No,Inicial/Pre-escolar,0.0,2007,NaN,NaN,NaN,NaN
14,1 22,3,Hijo/Hija,Sí,Sí,Mujer,18.0,Superior,1.0,12.0,Superior,No,NaN,NaN,NaN,NaN,NaN,1.0,NaN,No elegible,No,Inicial/Pre-escolar,0.0,Sí,Superior,12.0,2007,NaN,NaN,NaN,NaN

In [6]:
from mnp.config import INTERIM_DATA_DIR
import os
# Aseguramos que la carpeta interim exista
os.makedirs(INTERIM_DATA_DIR, exist_ok=True)
# Ruta del archivo final
output_path = INTERIM_DATA_DIR / "rech1_cleaned.parquet"
# Guardamos en formato parquet (preserva tipos de datos y ahorra RAM)
df_final.to_parquet(output_path, index=False)
print(f"[OK] Datos RECH1 (Fase 1, 2 y 3) guardados exitosamente en:")
print(f"-> {output_path}")

[OK] Datos RECH1 (Fase 1, 2 y 3) guardados exitosamente en:
-> /Users/abelguevarah/Desktop/invs/malnutrition-research/data/interim/rech1_cleaned.parquet

In [ ]:
import sweetviz as sv
from mnp.configs.column_labels import SWEETVIZ_LABELS
from mnp.config import INTERIM_DATA_DIR  # Importamos tu variable mágica

df_sweetviz = df_final.rename(columns=SWEETVIZ_LABELS)
reporte_sv = sv.analyze(df_sweetviz)

# Usamos la ruta absoluta inteligente y la pasamos a string
ruta_reporte = str(INTERIM_DATA_DIR / 'rech1_sweetviz_report.html')

reporte_sv.show_html(ruta_reporte)
reporte_sv.show_notebook(w="100%", h="800", filepath=ruta_reporte)

                                             |          | [  0%]   00:00 -> (? left)

NameError: name 'rech1_sweetviz_report' is not defined

In [ ]:
df_final['HV101'].value_counts(dropna=False)